# use an existing docker image as a base
FROM node:14.14.0-alpine

WORKDIR '/app'

#download and install dependencies
COPY ./package.json  ./
RUN npm install
COPY .  .

#Tell the image what to do when it starts as a container
CMD ["npm", "run", "dev"]